1.


Write a program that first asks the user for an integer and after that, a floating-point number. Finally, the program prints both numbers on the screen. The floating-point number shall be printed with two decimal places of precision.

Example output:
Enter an integer: 14
Enter a decimal number:3.123

You entered the integer: 14
You entered the decimal number, rounded to two decimal places: 3.12

The verification of program output does not account for whitespace characters like "\n", "\t" and " "



2.


Write a program that prompts the user for an amount in Finnish markka and converts it to euro. Finally, the program prints the amount on the screen in euro with two decimal places of precision. The euro conversion factor is 5.94573.

Hint:
You need three variables: one for the conversion factor, one for markka and one for euro. The required division can be accomplished by using the "/" character.

Example output:
Enter an amount in FIM:9.90
FIM converted to euro: 1.67

The verification of program output does not account for whitespace characters like "\n", "\t" and " "
